### ISSUE TITLE
Error while Running

### ISSUE THREAD

**Issue by tamanna-makkar** [typeorm/babel-example#2]
am getting this error: plz help if you can
Error:  { Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
    --------------------
    at Protocol._enqueue (/home/dixit/typeorm/babel-example/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/home/dixit/typeorm/babel-example/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at PoolConnection.connect (/home/dixit/typeorm/babel-example/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/dixit/typeorm/babel-example/node_modules/mysql/lib/Pool.js:48:16)
    at /home/dixit/typeorm/babel-example/node_modules/typeorm/driver/mysql/MysqlDriver.js:509:18
    at MysqlDriver.createPool (/home/dixit/typeorm/babel-example/node_modules/typeorm/driver/mysql/MysqlDriver.js:506:16)
    at MysqlDriver.<anonymous> (/home/dixit/typeorm/babel-example/node_modules/typeorm/driver/mysql/MysqlDriver.js:183:51)
    at step (/home/dixit/typeorm/babel-example/node_modules/typeorm/driver/mysql/MysqlDriver.js:32:23)
    at Object.next (/home/dixit/typeorm/babel-example/node_modules/typeorm/driver/mysql/MysqlDriver.js:13:53)
    at /home/dixit/typeorm/babel-example/node_modules/typeorm/driver/mysql/MysqlDriver.js:7:71
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3000,
  fatal: true }

**Comment by pleerock** [comment]
you don't have mysql running on port 3000.
